site_name: Ammódes Wiki
theme:
  name: material
  language: pt-BR
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
    - scheme: default
      primary: teal
      accent: cyan
  features:
    - navigation.sections
    - search.suggest
    - search.highlight

docs_dir: docs

plugins:
  - search
  - file-filter:
      only_doc_pages: true
      include_tag:
        - published
  - obsidian-bridge:
      invalid_link_attributes:
        - '.invalid'

markdown_extensions:
  - obsidian_media_mkdocs
  - obsidian_callouts
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css

exclude_docs: |
  mkdocs.yml
  LICENSE
  .github/**/*
  .obsidian/**/*
  templates/**/*