site_name: Ammódes Wiki
theme:
  name: material
  language: pt-BR
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
    - scheme: default
      primary: teal
      accent: cyan
  features:
    - navigation.sections
    - search.suggest
    - search.highlight

docs_dir: .

plugins:
  - search
  - ezlinks:
      obsidian_syntax: true
      base_dir: .
  - callouts

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

exclude_docs: |
  mkdocs.yml
  LICENSE
  .github/**/*
  .obsidian/**/*
  templates/**/*
  _temp_private/**/*
